#!/bin/sh
set -e

cat <<EOF > "/etc/nginx/sites-enabled/default"
server {
  listen 80 default_server;
  root /var/www/html;

  location /helloworld {
    brotli_static on;
  }
}
EOF

mkdir -p /var/www/html
echo 'hello world' | brotli -9 > /var/www/html/helloworld.br

exp="hello world
response_code: 200"

nginx -t
invoke-rc.d nginx restart || { journalctl -n all -xu nginx.service; exit 1; }

out=`curl --compressed --fail -w "response_code: %{http_code}\n" http://127.0.0.1/helloworld`

if [ x"${out}" != x"${exp}" ]; then
  echo "output:"
  echo "====================="
  echo "${out}"
  echo "====================="
  echo "expected output:"
  echo "====================="
  echo "${exp}"
  echo "====================="
  exit 1
fi
